### ISSUE TITLE
Doesn't work with controller

### ISSUE THREAD

**Issue by ExpDev07** [peopleconnectus/ember-paypal-button#35]
Hey! I have the following code:

! templates/varsel/betaling.hbs
`<section class="tight left form">
    {{paypal-button
        isEnabled=isEnabled
        payment=(action payment)
        onAuthorize=(action onAuthorize)
        onCancel=(action onCancel)
        onError=(action onError)
    }}
</section>`

! controllers/varsel/betaling.js
`export default Controller.extend({
    
    actions: {
        payment(a) {
            console.log('1');
        },

        onAuthorize(data, actions) {
            console.log('2');
        },

        onCancel(a) {
            console.log('3');
        },

        onError(a) {
            console.log('4');
        }
    } 
});`

And when trying to access the betaling route, I am presented with the error: `Assertion Failed: Action passed is null or undefined in (action) from <smitta@controller:varsel/betaling::ember185>.`

**Comment by psheraton** [comment]
I think you may be missing quotes around your actions
ie:
`payment=(action "payment")`

**Comment by ExpDev07** [comment]
You're right! Thanks.
